name: Deploy Site

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blogdown Source (Including Submodules)
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure public/ submodule is fetched

      - name: Install Hugo 0.120.0
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.120.0/hugo_extended_0.120.0_linux-amd64.deb
          sudo dpkg -i hugo_extended_0.120.0_linux-amd64.deb
          hugo version

      - name: Build Site
        run: |
          hugo --minify
          if [ ! -d "public" ]; then
            echo "Error: Hugo did not generate the public/ directory!"
            exit 1
          fi
          ls -l public  # Debugging output

      - name: Commit and Push Changes to Submodule
        run: |
          cd public
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update generated site from Blogdown" || echo "No changes to commit"
          git push origin main
